Repository nRF24/RF24, pull requests merged in 2024-03, with the labels that each got.

#956 separate ISR handling from IRQ processing
  examples/InterruptConfigure/InterruptConfigure.ino
  examples_linux/interruptConfigure.cpp
  examples_pico/interruptConfigure.cpp
Labels: enhancement

#955 Promiscuous scanners
  .github/workflows/build_linux.yml
  .gitignore
  examples/scanner/scanner.ino
  examples/scannerGraphic/scannerGraphic.ino
  examples_linux/CMakeLists.txt
  examples_linux/ncurses/CMakeLists.txt
  examples_linux/ncurses/scanner_curses.cpp
  examples_linux/scanner.cpp
  examples_linux/scanner.py
  examples_pico/scanner.cpp
Labels: enhancement

#959 Update SPIDEV driver for Character Device v2 ABI; cache FDs
  CMakeLists.txt
  utility/SPIDEV/RF24_arch_config.h
  utility/SPIDEV/gpio.cpp
  utility/SPIDEV/gpio.h
Labels: enhancement

#961 IRQ support using Linux kernel Character Device + Posix threads
  .github/workflows/build_linux.yml
  CMakeLists.txt
  Makefile
  configure
  examples_linux/CMakeLists.txt
  examples_linux/Makefile
  examples_linux/Makefile.examples
  examples_linux/acknowledgementPayloads.cpp
  examples_linux/gettingstarted.cpp
  examples_linux/interruptConfigure.cpp
  examples_linux/manualAcknowledgements.cpp
  examples_linux/multiceiverDemo.cpp
  examples_linux/ncurses/CMakeLists.txt
  examples_linux/ncurses/scanner_curses.cpp
  examples_linux/readme.md
  examples_linux/scanner.cpp
  examples_linux/streamingData.cpp
  pyRF24/setup.py
  utility/CMakeLists.txt
  utility/MRAA/RF24_arch_config.h
  utility/MRAA/compatibility.cpp
  utility/MRAA/compatibility.h
  utility/MRAA/gpio.h
  utility/MRAA/spi.h
  utility/RPi/RF24_arch_config.h
  utility/RPi/compatibility.cpp
  utility/RPi/compatibility.h
  utility/RPi/includes.h
  utility/RPi/interrupt.cpp
  utility/RPi/interrupt.h
  utility/SPIDEV/RF24_arch_config.h
  utility/SPIDEV/compatibility.cpp
  utility/SPIDEV/compatibility.h
  utility/SPIDEV/gpio.cpp
  utility/SPIDEV/gpio.h
  utility/SPIDEV/includes.h
  utility/SPIDEV/interrupt.cpp
  utility/SPIDEV/interrupt.h
  utility/SPIDEV/spi.cpp
  utility/SPIDEV/spi.h
  utility/Template/compatibility.h
  utility/Template/includes.h
  utility/Template/spi.h
  utility/pigpio/RF24_arch_config.h
  utility/pigpio/compatibility.cpp
  utility/pigpio/compatibility.h
  utility/pigpio/gpio.cpp
  utility/pigpio/gpio.h
  utility/pigpio/includes.h
  utility/pigpio/interrupt.cpp
  utility/pigpio/interrupt.h
  utility/pigpio/spi.cpp
  utility/pigpio/spi.h
  utility/wiringPi/RF24_arch_config.h
  utility/wiringPi/includes.h
  utility/wiringPi/interrupt.h
  utility/wiringPi/spi.cpp
  utility/wiringPi/spi.h
Labels: enhancement

#964 Add link to RF24G library in docs
  docs/main_page.md
Labels: documention

#966 revise MRAA driver's GPIO implementation
  RF24.cpp
  RF24.h
  utility/MRAA/RF24_arch_config.h
  utility/MRAA/gpio.cpp
  utility/MRAA/gpio.h
Labels: enhancement

#967 update python wrapper/examples/doc
  .github/workflows/doxygen.yml
  docs/Doxyfile
  docs/doxygen-custom.css
  docs/python_wrapper.md
  examples_linux/acknowledgementPayloads.cpp
  examples_linux/acknowledgement_payloads.py
  examples_linux/getting_started.py
  examples_linux/gettingstarted.cpp
  examples_linux/interruptConfigure.cpp
  examples_linux/interrupt_configure.py
  examples_linux/interrupts/transfer_interrupt.cpp
  examples_linux/manualAcknowledgements.cpp
  examples_linux/manual_acknowledgements.py
  examples_linux/multiceiverDemo.cpp
  examples_linux/multiceiver_demo.py
  examples_linux/ncurses/scanner_curses.cpp
  examples_linux/scanner.cpp
  examples_linux/scanner.py
  examples_linux/streamingData.cpp
  examples_linux/streaming_data.py
  pyRF24/pyRF24.cpp
Labels: enhancement, documention
